spreadsheet_name = "transactions"
credentials_json = """{
  "type": "service_account",
  "project_id": "...",
  "private_key_id": "...",
  "private_key": "-----BEGIN PRIVATE KEY-----\\n....\\n-----END PRIVATE KEY-----\\n",
  "client_email": "...",
  ...
}"""
